### ISSUE TITLE
Oura?

### ISSUE THREAD

**Issue by winkler1** [jeffshek/betterself#435]
Hi-
 Not really an issue, but might serve as breadcrumbs instead of emailing directly. Do any of you folks have an Oura ring? It has loads of good sleep data and an API - https://cloud.ouraring.com/docs/
 I'd love a minimal data-entry scenario like SnoreLab remedies has - https://snorelab.com/wp-content/uploads/2017/12/snorelab-iphone-landing-5-uai-258x414.jpg - to know the impact of glycine, magnesium, mouth taping etc :)
 Checking off 3 checkboxes for these factors, clicking Submit, then having correlations updated in the AM when synching Oura to dashboard would be an ideal workflow

**Comment by jeffshek** [comment]
thanks for this - i don't, but i'll figure out a way to try to test w/their api in the next upcoming months 

if you're still interested, i'll email you when done!
